name: status_bar_tap
description: A Flutter package that enables scroll-to-top functionality when tapping the status bar (iOS) or top area (Android). Supports platform-specific configuration.
version: 1.0.2
homepage: https://github.com/Twwan/status_bar_tap
repository: https://github.com/Twwan/status_bar_tap

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

example:
  - lib/main.dart
  - lib/single_controller_screen.dart
  - lib/multiple_controllers_screen.dart
